version: '2.2'

services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - IM_CA_PASSWORD=$IM_CA_PASSWORD
      - IM_CERT_PASSWORD=$IM_CERT_PASSWORD
    command: >
      bash -c '
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --keep-ca-key -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs; 
          echo "IM_CA_PASSWORD=${IM_CA_PASSWORD}"
          echo "IM_CERT_PASSWORD=${IM_CERT_PASSWORD}"
          sh ./config/certificates/make-p12.sh
        fi;
        chown -R 1000:0 /certs
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/certs', '.:/usr/share/elasticsearch/config/certificates']

volumes: {"certs"}