version: '2.2'
x-environment:
  &common-env
  IM_INTERNAL_CERTS: &IM_INTERNAL_CERTS $IM_INTERNAL_CERTS
  RELEASE: &RELEASE $RELEASE
services:
  aiimi-elastic:
    container_name: ${RELEASE}-elastic
    image: aiimilabs/es:0.0.4
    environment:
      node.name: ${RELEASE}-elastic
    ports:
      - 9200:9200
    volumes: [ 'certs:$IM_INTERNAL_CERTS' ]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -k -XGET https://localhost:9200 | grep -q 'missing authentication credentials'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120
volumes: { "certs" }
