version: '2.2'
x-environment:
  &common-env
  RELEASE: &RELEASE $RELEASE
  IM_INTERNAL_CERTS: &CERTS_DIR $IM_INTERNAL_CERTS
  IM_PORT_ADMIN_API: &IM_PORT_ADMIN_API $IM_PORT_ADMIN_API
  IM_PORT_SEARCH_API: &IM_PORT_SEARCH_API $IM_PORT_SEARCH_API
  IM_PORT_DS_API: &IM_PORT_DS_API $IM_PORT_DS_API
  IM_HOST_ADMIN_API: &IM_HOST_ADMIN_API $IM_HOST_ADMIN_API
  IM_HOST_SEARCH_API: &IM_HOST_SEARCH_API $IM_HOST_SEARCH_API
  IM_HOST_DS_API: &IM_HOST_DS_API $IM_HOST_DS_API
  IM_HOST_FRONTEND: &IM_HOST_FRONTEND $IM_HOST_FRONTEND
services:
  ingress:
    container_name: ${RELEASE}-ingress
    image: nginx
    volumes:
      [
        'certs:$IM_INTERNAL_CERTS',
        './nginx:/etc/nginx/templates'
      ]
    environment:
      <<: *common-env
    restart: "no"
    ports:
      - 443:443
    # command: bash -c "rm --interactive=never /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    # command: bash -c "nginx -g 'daemon off;'"
    # command: nginx -g 'daemon off;'
volumes: { "certs" }
