version: '2.2'
x-environment:
  &common-env
  RELEASE: &RELEASE $RELEASE
  ELASTICSEARCH_HOSTS: &ELASTICSEARCH_HOSTS $ELASTICSEARCH_HOSTS
  IM_ELASTIC_USER: &IM_ELASTIC_USER $IM_ELASTIC_USER
  IM_ELASTIC_PASSWORD: &IM_ELASTIC_PASSWORD $IM_ELASTIC_PASSWORD
  IM_INTERNAL_CERTS: &CERTS_DIR $IM_INTERNAL_CERTS
  IM_PORT_ADMIN_API: &IM_PORT_ADMIN_API $IM_PORT_ADMIN_API
  IM_PORT_SEARCH_API: &IM_PORT_SEARCH_API $IM_PORT_SEARCH_API
  IM_PORT_DS_API: &IM_PORT_DS_API $IM_PORT_DS_API
  IM_HOST_ADMIN_API: &IM_HOST_ADMIN_API $IM_HOST_ADMIN_API
  IM_HOST_SEARCH_API: &IM_HOST_SEARCH_API $IM_HOST_SEARCH_API
  IM_HOST_DS_API: &IM_HOST_DS_API $IM_HOST_DS_API
  IM_HOST_FRONTEND: &IM_HOST_FRONTEND $IM_HOST_FRONTEND
services:
  kibana:
    container_name: ${RELEASE}-kibana
    image: docker.elastic.co/kibana/kibana:7.17.0
    volumes: ['certs:$IM_INTERNAL_CERTS']
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=$ELASTICSEARCH_HOSTS
      - XPACK_SECURITY_ENABLED=true
      - ELASTICSEARCH_USERNAME=$IM_ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$IM_ELASTIC_PASSWORD
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$IM_INTERNAL_CERTS/ca/ca.crt
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate
      - SERVER_SSL_ENABLED=false
      # - "wait_until_ready"
volumes: { "certs" }
